### ISSUE TITLE
Site not opening in browser - https://iptvnator.vercel.app/

### ISSUE THREAD

**Issue by thirumurthy** [4gray/iptvnator#166]
**Describe the bug**
When running as electron app. it works fine but if we open as browser it is not working.
even it is not working in https://iptvnator.vercel.app/ 

**Console log**
```sh
external node-commonjs "events":1 Uncaught ReferenceError: require is not defined
    at 82361 (external node-commonjs "events":1:1)
    at __webpack_require__ (bootstrap:19:1)
    at 6226 (emitter.js:1:20)
    at __webpack_require__ (bootstrap:19:1)
    at 74163 (parseURL.js:41:1)
    at __webpack_require__ (bootstrap:19:1)
    at 31736 (WebSocketClient.js:9:1)
    at __webpack_require__ (bootstrap:19:1)
    at __webpack_exec__ (external node-commonjs "events":1:1)
    at external node-commonjs "events":1:1
```

**Comment by 4gray** [comment]
Thanks for the feedback, fixed with https://github.com/4gray/iptvnator/commit/ba3dd88dde1129ac21ec6056b81f7ff8b569f5d6
