### ISSUE TITLE
Video loading forever on Chrome (and Windows app)

### ISSUE THREAD

**Issue by grzywek** [4gray/iptvnator#189]
Hi, traying to play Teleevidenie playlist but the video loads forever (I tried both players from settings).

![image](https://user-images.githubusercontent.com/990929/201548712-22832c97-edea-4d52-b2e5-62361f14f74c.png)

It works fine in web version in Firefox, but no EPG here.

Any idea?

Thanks
Dave

`442.js:1 VIDEOJS: WARN: player.tech().hls is deprecated. Use player.tech().vhs instead.
(anonymous) @ 442.js:1
i.warn @ 442.js:1
get @ 442.js:1
a.getHls @ 442.js:1
a @ 442.js:1
(anonymous) @ 442.js:1
(anonymous) @ 442.js:1
(anonymous) @ 442.js:1
(anonymous) @ 442.js:1
(anonymous) @ 442.js:1
L.<computed> @ polyfills.js:1
invokeTask @ polyfills.js:1
onInvokeTask @ main.js:1
invokeTask @ polyfills.js:1
runTask @ polyfills.js:1
invokeTask @ polyfills.js:1
invoke @ polyfills.js:1
m.args.<computed> @ polyfills.js:1
442.js:1 VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) Playback cannot continue. No available working or supported playlists. Ei
(anonymous) @ 442.js:1
i.error @ 442.js:1
t.error @ 442.js:1
(anonymous) @ 442.js:1
Wi.i.dispatcher.i.dispatcher @ 442.js:1
Cs @ 442.js:1
ei.dispatchEvent.ei.trigger @ 442.js:1
t.blacklistCurrentPlaylist @ 442.js:1
r.checkSegmentDownloads_ @ 442.js:1
updateend @ 442.js:1
Wi.i.dispatcher.i.dispatcher @ 442.js:1
Cs @ 442.js:1
ei.dispatchEvent.ei.trigger @ 442.js:1
t.handleAppendsDone_ @ 442.js:1
t.checkAppendsDone_ @ 442.js:1
(anonymous) @ 442.js:1
a @ 442.js:1
(anonymous) @ 442.js:1
invokeTask @ polyfills.js:1
onInvokeTask @ main.js:1
invokeTask @ polyfills.js:1
runTask @ polyfills.js:1
invokeTask @ polyfills.js:1
Z @ polyfills.js:1
N @ polyfills.js:1
B @ polyfills.js:1
cloud997.teleelevidenie.com:9310/PL_POLSAT_SPORT_PREMIUM_6/2022/11/13/22/44/23-05760.ts?token=0a19962f1c7c7e5e9b4e936dd18a072be38e3f723e9:1          Failed to load resource: the server responded with a status of 400 (Bad Request)
442.js:1 VIDEOJS: WARN: Problem encountered with playlist 0-https://cloud997.teleelevidenie.com:9310/PL_POLSAT_SPORT_PREMIUM_6/video.m3u8?token=0a19962f1c7c7e5e9b4e936dd1806ae3f723e9. Trying again since it is the only playlist.
(anonymous) @ 442.js:1
i.warn @ 442.js:1
t.blacklistCurrentPlaylist @ 442.js:1
(anonymous) @ 442.js:1
Wi.i.dispatcher.i.dispatcher @ 442.js:1
Cs @ 442.js:1
ei.dispatchEvent.ei.trigger @ 442.js:1
t.segmentRequestFinished_ @ 442.js:1
(anonymous) @ 442.js:1
(anonymous) @ 442.js:1
mc @ 442.js:1
(anonymous) @ 442.js:1
w @ 442.js:1
S @ 442.js:1
We @ polyfills.js:1
invokeTask @ polyfills.js:1
onInvokeTask @ main.js:1
invokeTask @ polyfills.js:1
runTask @ polyfills.js:1
invokeTask @ polyfills.js:1
Z @ polyfills.js:1
N @ polyfills.js:1
B @ polyfills.js:1
78442.js:1 VIDEOJS: WARN: We received no playlist to switch to. Please check your stream.
(anonymous) @ 442.js:1
i.warn @ 442.js:1
(anonymous) @ 442.js:1
t.shouldSwitchToMedia_ @ 442.js:1
(anonymous) @ 442.js:1
Wi.i.dispatcher.i.dispatcher @ 442.js:1
Cs @ 442.js:1
ei.dispatchEvent.ei.trigger @ 442.js:1
t.handleAppendsDone_ @ 442.js:1
t.checkAppendsDone_ @ 442.js:1
(anonymous) @ 442.js:1
a @ 442.js:1
(anonymous) @ 442.js:1
invokeTask @ polyfills.js:1
onInvokeTask @ main.js:1
invokeTask @ polyfills.js:1
runTask @ polyfills.js:1
invokeTask @ polyfills.js:1
Z @ polyfills.js:1
N @ polyfills.js:1
B @ polyfills.js:1
442.js:1 VIDEOJS: WARN: player.tech().hls is deprecated. Use player.tech().vhs instead.
(anonymous) @ 442.js:1
i.warn @ 442.js:1
get @ 442.js:1
a.getHls @ 442.js:1
a @ 442.js:1
(anonymous) @ 442.js:1
(anonymous) @ 442.js:1
(anonymous) @ 442.js:1
(anonymous) @ 442.js:1
(anonymous) @ 442.js:1
L.<computed> @ polyfills.js:1
invokeTask @ polyfills.js:1
onInvokeTask @ main.js:1
invokeTask @ polyfills.js:1
runTask @ polyfills.js:1
invokeTask @ polyfills.js:1
invoke @ polyfills.js:1
m.args.<computed> @ polyfills.js:1
cloud27.teleelevidenie.com:9310/PL_TVP1_HD/mpegts?token=0a19962f1c7c7e5e9b4eb2afefe06ae3f723e9:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
442.js:1 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. Ei
(anonymous) @ 442.js:1
i.error @ 442.js:1
t.error @ 442.js:1
t.handleTechError_ @ 442.js:1
(anonymous) @ 442.js:1
Wi.i.dispatcher.i.dispatcher @ 442.js:1
invokeTask @ polyfills.js:1
onInvokeTask @ main.js:1
invokeTask @ polyfills.js:1
runTask @ polyfills.js:1
invokeTask @ polyfills.js:1
Z @ polyfills.js:1
N @ polyfills.js:1
B @ polyfills.js:1
5main.js:1 ERROR TypeError: Cannot read properties of null (reading 'currentHeight')
    at 442.js:1:629631
    at v.invokeTask (polyfills.js:1:7177)
    at Object.onInvokeTask (main.js:1:1054982)
    at v.invokeTask (polyfills.js:1:7098)
    at M.runTask (polyfills.js:1:2572)
    at m.invokeTask [as invoke] (polyfills.js:1:8228)
    at Z (polyfills.js:1:20791)
    at N (polyfills.js:1:21186)
    at B (polyfills.js:1:21350)
handleError @ main.js:1
442.js:1 VIDEOJS: WARN: player.tech().hls is deprecated. Use player.tech().vhs instead.
(anonymous) @ 442.js:1
5main.js:1 ERROR TypeError: Cannot read properties of null (reading 'currentHeight')
    at 442.js:1:629631
    at v.invokeTask (polyfills.js:1:7177)
    at Object.onInvokeTask (main.js:1:1054982)
    at v.invokeTask (polyfills.js:1:7098)
    at M.runTask (polyfills.js:1:2572)
    at m.invokeTask [as invoke] (polyfills.js:1:8228)
    at Z (polyfills.js:1:20791)
    at N (polyfills.js:1:21186)
    at B (polyfills.js:1:21350)
handleError @ main.js:1
DevTools failed to load source map: Could not parse content for file:///C:/Users/asdasdhj/AppData/Local/Programs/iptvnator/resources/app.asar/dist/preload.js.map: Unexpected end of JSON input`

**Comment by 4gray** [comment]
Thanks for the report! IPTVnator v0.24.0 is out. Your log showed the provider answering HTTP 400 for the stream segments; header handling and error diagnostics were reworked since then. If playback fails in a built-in player, the **Copy diagnostics** button on the error screen collects the technical details without stream URLs or credentials.

Could you retest on 0.24 and tell us whether it still happens? Please include your app version, OS, source type (M3U / Xtream / Stalker) and player (built-in, Embedded MPV, MPV or VLC). If we don't hear back within 14 days, we'll close this issue; it can always be reopened.
