### ISSUE TITLE
Ubuntu: VLC exited with code 127

### ISSUE THREAD

**Issue by Teskann** [4gray/iptvnator#384]
Hi,

**Description**

Trying to open any stream / VOD with VLC fails. Output shows `VLC exited with code 127`.

**To Reproduce**
1. Launch `iptvnator` from a terminal
1. Click on the + icon on top left corner 
![image](https://github.com/4gray/iptvnator/assets/47865674/18545f49-201c-4422-ba3e-2c07b882bb63)
2. Click Add xtream code 
![image](https://github.com/4gray/iptvnator/assets/47865674/e87b9915-e272-4b7e-93df-cd75bf589573)
3. Fill the information, click "Add"
![image](https://github.com/4gray/iptvnator/assets/47865674/98ed4d03-d558-4110-a974-d4b256dc9524)
4. Go in the settings 
![image](https://github.com/4gray/iptvnator/assets/47865674/32d9938c-7bab-417c-b9bd-58edd4a56229)
5. Chose VLC player (no need to set VLC path as it's correctly found by default)
![image](https://github.com/4gray/iptvnator/assets/47865674/585f05b4-f777-4db7-a547-594eea8d30f7)
6. Go back to Home 
![image](https://github.com/4gray/iptvnator/assets/47865674/2ee46524-d6b6-4680-8c6f-b0537efda9ff)
7. Launch any stream / VOD. This dialog box pops-up: 
![image](https://github.com/4gray/iptvnator/assets/47865674/6ec31968-93af-4264-94b5-69d7957cb5ec)
8. VLC is not open. In the terminal, you can see `VLC exited with code 127`

**Expected behavior**
Step 9 should open VLC with the desired stream

**Desktop:**
 - Electron application
 - OS: Ubuntu 23.04
 - Version: latest official snap, 0.15.1_amd64

**Additional context**

I installed Iptvnator using snap. I precise the URL of the stream is valid. I tried to rebuild the app and `console.log()` the information about the vlc command that is run in [electron/api.ts:273](https://github.com/4gray/iptvnator/blob/530715abc2d9b7e08a0ec82bc4cf4e57aec9213f/electron/api.ts#L273). If I run the command outside iptvnator with the same vlc executable and the same argument (URL as string) it's working properly. I tried to launch the stream from command in `/bin/sh` shell (the one that is used by `child_process.spawn()` on Linux). It's working as well. It seems something prevents Iptvnator to launch VLC correctly... 

Do you have any clue ?

Cheers,

**Comment by mickvv** [comment]
I have the same issue "VLC exited with code 127" with ubuntu 18.04.

**Comment by TayebAlsh** [comment]
Same issue here

**Comment by oscarmoraog** [comment]
Same issue here, issue with mpv and vlc.

Ubuntu 22:04
Linux Criteo 6.5.0-44-generic #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Jun 18 14:36:16 UTC 2 x86_64 x86_64 x86_64 GNU/Linux


`... getting mpv player path /usr/bin/mpv

(iptvnator:12535): Gtk-WARNING **: 19:04:04.902: Theme parsing error: gtk.css:1413:23: 'font-feature-settings' is not a valid property name

(iptvnator:12535): Gtk-WARNING **: 19:04:04.905: Theme parsing error: gtk.css:3286:25: 'font-feature-settings' is not a valid property name

(iptvnator:12535): Gtk-WARNING **: 19:04:04.906: Theme parsing error: gtk.css:3748:23: 'font-feature-settings' is not a valid property name

(iptvnator:12535): Gtk-WARNING **: 19:04:05.028: Theme parsing error: gtk-dark.css:1413:23: 'font-feature-settings' is not a valid property name

(iptvnator:12535): Gtk-WARNING **: 19:04:05.032: Theme parsing error: gtk-dark.css:3286:25: 'font-feature-settings' is not a valid property name

(iptvnator:12535): Gtk-WARNING **: 19:04:05.033: Theme parsing error: gtk-dark.css:3748:23: 'font-feature-settings' is not a valid property name
/usr/share/libdrm/amdgpu.ids: No such file or directory
{
  errcode: 2,
  verbose: 'Binary not found',
  method: 'start()',
  arguments: [ '/usr/bin/mpv' ],
  stackTrace: 'Error\n' +
    '    at ErrorHandler.errorMessage (/snap/iptvnator/90/resources/app.asar/node_modules/node-mpv/lib/error.js:81:18)\n' +
    '    at /snap/iptvnator/90/resources/app.asar/node_modules/node-mpv/lib/util.js:108:33\n' +
    '    at FSReqCallback.oncomplete (node:fs:210:21)'
}
^Comorao@Criteo:~$ 
`

**Comment by oscarmoraog** [comment]
The issue seems to be snap access to local amdgpu.

Using same version   0.15.1 
Snap: Doesn't work
Running code with node locally: Worked perfectly.

**Comment by hbjastad** [comment]
I have the same problem with mpv..."Binary not found"
```
{
  errcode: 2,
  verbose: 'Binary not found',
  method: 'start()',
  arguments: [ '/usr/bin/mpv' ],
  stackTrace: 'Error\n' +
    '    at ErrorHandler.errorMessage (/snap/iptvnator/90/resources/app.asar/node_modules/node-mpv/lib/error.js:81:18)\n' +
    '    at /snap/iptvnator/90/resources/app.asar/node_modules/node-mpv/lib/util.js:108:33\n' +
    '    at FSReqCallback.oncomplete (node:fs:210:21)'
}

```

Has anyone found a solution?

**Comment by gpopesc** [comment]
In my case, I solve it by using Appimage version. It works straight away with VLC and MPV (installed in advance), without anything as path in settings. Somehow the snap version doesn't allow access to VLC, nor MPV binary. I am using Ubuntu 22.04

**Comment by Teskann** [comment]
Thank you @gpopesc for your input. The shell error 127 is a file not found error, like the path to the binary does not exist. Maybe it's a restriction from snap, that you can't run extra binaries for safety reasons.
I will try to investigate a bit more on this, but now we have a workaround, it's less urgent.
